sonar.projectKey=kiosko-frontend
sonar.projectName=Kiosko Multimedia - Frontend
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8
sonar.sources=src/app
sonar.tests=src/app
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/kioskomultimedia/lcov.info